### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by GoldenEggsStudio** [BuSheTeam/GoldenEggs#3]
使用侧边栏的公告、官方消息、讨论时，点击就直接退出了。还有就是右上角的Settings就是个摆设？

**Comment by BuSheTeam** [comment]
是在什么环境下出现的问题呢？(手机型号  Android系统版本 问题出现时网络状态)

**Comment by GoldenEggsStudio** [comment]
mumu模拟器2.0.35（只安装了碧蓝、FGO）、魅族MX5（安卓版本5.1，安卓补丁日期2.17年4月5日，Flyme 6.3.0.0A），网络都是北京移动、连接的5G频率下的wifi

**Comment by BuSheTeam** [comment]
请等候我们放出 Beta 分支，届时请使用 Beta - 此问题编号 版尝试使用相同环境还原问题。

**Comment by BuSheTeam** [comment]
and Settings 目前似乎就是个摆设😄

**Comment by BuSheTeam** [comment]
当前问题已经修复。

**Comment by BuSheTeam** [comment]
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.loadUrl(java.lang.String)' on a null object reference
       at work.bushe.goldeneggs.MainActivity.onNavigationItemSelected(MainActivity.java:135)
       at com.google.android.material.navigation.NavigationView$1.onMenuItemSelected(NavigationView.java:174)
       at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
       at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
       at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
       at com.google.android.material.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:368)
       at android.view.View.performClick(View.java:6311)
       at android.view.View$PerformClick.run(View.java:24791)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6602)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:453)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)`
